/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare16b_16 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg [15:0] cmp
  );
  
  
  
  always @* begin
    cmp = 16'h0000;
    
    case (alufn[1+1-:2])
      2'h1: begin
        cmp[0+0-:1] = z;
      end
      2'h2: begin
        cmp[0+0-:1] = ~n & v | n & ~v;
      end
      2'h3: begin
        cmp[0+0-:1] = z | (~n & v | n & ~v);
      end
      default: begin
        cmp[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
